apiVersion: v1
data:
  BACCARAT_URL: https://rtp.royalgaming.online/result/baccarat
  CASINO_HOLDEM_URL: https://rtp.royalgaming.online/result/casino_holdem
  DB_CLUSTER: bvtld.mongodb.net
  DB_CLUSTER_NAME: rgprod
  DB_CONNECTION_URL: mongodb+srv://rgadmin:YyICeTMB1sYvBC6d@rgprod.bvtld.mongodb.net/rgprod?readPreference=primary&retryWrites=true&ssl=true
  DB_DATABASE: rgprod
  ENV_URL: https://settlement.royalgaming.online
  HYPEX_SALT: 3309d355-0e71-4e1f-86ac-535056ce76c6
  KAFKA_BROKERS: b-2.prodcluster.d5zvkc.c3.kafka.eu-west-2.amazonaws.com:9092,b-1.prodcluster.d5zvkc.c3.kafka.eu-west-2.amazonaws.com:9092,b-3.prodcluster.d5zvkc.c3.kafka.eu-west-2.amazonaws.com:9092
  MUFLISTEENPATTI_URL: https://rtp.royalgaming.online/result/teen_muflis
  REDIS_ADDRESS: redis-prod.6ymrvw.ng.0001.euw2.cache.amazonaws.com:6379
  REDIS_DB: "0"
  REDIS_HOST: redis-prod.6ymrvw.ng.0001.euw2.cache.amazonaws.com
  REDIS_MAX_RETRIES: "5"
  REDIS_PORT: "6379"
  REDIS_READER: redis-prod-ro.6ymrvw.ng.0001.euw2.cache.amazonaws.com:6379
  SETTLEMENT_URI: https://settlement.royalgaming.online/api/v1/core/settle-open-bets
  TEENPATTI_URL: https://rtp.royalgaming.online/result/teen_patti
  TEST_BASE_URL: https://royalgaming.online
  TEST_GAME_LAUNCH_URL: '%s?token=%s&operatorId=%s&userName=%s&partnerId=%s&providerId=%s&lobby=%s&gameId=%s&opentable=%s'
  TEST_LOBBY_URL: '%s/auth?token=%s&operatorId=%s&partnerId=%s&providerId=%s'
  TEST_OPERATOR: TestOperator
  TEST_OPERATOR_BASE_URL: https://game.royalgaming.online
  TEST_OPERATOR_LOBBY_URL: '%s?token=%s&operatorId=%s&partnerId=%s&providerId=%s&lobby=%s'
  TEST_TOKEN: f23004ee-2bf4-49b9-a98b-f0189520b795
  VIDEO_URL: https://www.youtube.com/embed/rKspGEzJ8eU?rel=0&modestbranding=1&autohide=1&autoplay=1&loop=1&showinfo=0&controls=0
  WEBSOCKET_URL: feed.royalgaming.online
kind: ConfigMap
metadata:
  name: app-configs
  namespace: NAMESPACE
