{{- if .Values.cron.enabled -}}
{{- $fullName := include "myapp.fullname" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}
  namespace:  {{ $fullName }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: {{ .Values.image.repository }}
              imagePullPolicy: IfNotPresent
              name: {{ $fullName }}
              envFrom:
              - configMapRef:
                  name: app-configs
                  optional: true
              - secretRef:
                  name: app-secrets
                  optional: true
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
{{- end }}

